"""add created_for_users

Revision ID: b5ef57751578
Revises: 90c32b1019d3
Create Date: 2018-06-08 17:38:05.593598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ef57751578'
down_revision = '90c32b1019d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
