"""test

Revision ID: be24888801eb
Revises: f44f069a8e78
Create Date: 2018-06-10 18:20:55.471196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be24888801eb'
down_revision = 'f44f069a8e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
