"""add2 posts(Base)

Revision ID: f44f069a8e78
Revises: d86c16d45f54
Create Date: 2018-06-10 17:01:34.603324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44f069a8e78'
down_revision = 'd86c16d45f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
